{"links": {"self": {"href": "data/repositories/osrf/gazebojs/pullrequests/18/comments/20974642.json"}, "html": {"href": "#!/osrf/gazebojs/pull-requests/18/_/diff#comment-20974642"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 18, "links": {"self": {"href": "data/repositories/osrf/gazebojs/pullrequests/18.json"}, "html": {"href": "#!/osrf/gazebojs/pull-requests/18"}}, "title": "new  poses filter tests added"}, "content": {"raw": "The filter test looks good. However, when I run npm test, I get the following error in the performance test:\n\n```\n1880 messages received in 4 seconds, 470 messages/sec\n1880 messages received in 4 seconds, 470 messages/sec\n1880 messages received in 4 seconds, 470 messages/sec\n1880 messages received in 4 seconds, 470 messages/sec\n1880 messages received in 4 seconds, 470 messages/sec\n1880 messages received in 4 seconds, 470 messages/sec\n1880 messages received in 4 seconds, 470 messages/sec\n1880 messages received in 4 seconds, 470 messages/sec\n1880 messages received in 4 seconds, 470 messages/sec\n1880 messages received in 4 seconds, 470 messages/sec\n    2) No filter\nsuiteTeardown\n\n\n  9 passing (11s)\n  2 failing\n\n  1) performance Reciving msgs:\n     Error: done() called multiple times\n      at multiple (/home/hugo/code/gsoc/gazebojs/node_modules/mocha/lib/runnable.js:194:31)\n      at done (/home/hugo/code/gsoc/gazebojs/node_modules/mocha/lib/runnable.js:201:26)\n      at /home/hugo/code/gsoc/gazebojs/node_modules/mocha/lib/runnable.js:226:9\n      at Timeout._onTimeout (/home/hugo/code/gsoc/gazebojs/test/test_performance.js:71:17)\n      at tryOnTimeout (timers.js:224:11)\n      at Timer.listOnTimeout (timers.js:198:5)\n\n\n```\n\nSurprisingly, the performance test works fine in the default branch. \nAre you seeing the same issues? \n\n\n", "markup": "markdown", "html": "<p>The filter test looks good. However, when I run npm test, I get the following error in the performance test:</p>\n<div class=\"codehilite\"><pre><span></span>1880 messages received in 4 seconds, 470 messages/sec\n1880 messages received in 4 seconds, 470 messages/sec\n1880 messages received in 4 seconds, 470 messages/sec\n1880 messages received in 4 seconds, 470 messages/sec\n1880 messages received in 4 seconds, 470 messages/sec\n1880 messages received in 4 seconds, 470 messages/sec\n1880 messages received in 4 seconds, 470 messages/sec\n1880 messages received in 4 seconds, 470 messages/sec\n1880 messages received in 4 seconds, 470 messages/sec\n1880 messages received in 4 seconds, 470 messages/sec\n    2) No filter\nsuiteTeardown\n\n\n  9 passing (11s)\n  2 failing\n\n  1) performance Reciving msgs:\n     Error: done() called multiple times\n      at multiple (/home/hugo/code/gsoc/gazebojs/node_modules/mocha/lib/runnable.js:194:31)\n      at done (/home/hugo/code/gsoc/gazebojs/node_modules/mocha/lib/runnable.js:201:26)\n      at /home/hugo/code/gsoc/gazebojs/node_modules/mocha/lib/runnable.js:226:9\n      at Timeout._onTimeout (/home/hugo/code/gsoc/gazebojs/test/test_performance.js:71:17)\n      at tryOnTimeout (timers.js:224:11)\n      at Timer.listOnTimeout (timers.js:198:5)\n</pre></div>\n\n\n<p>Surprisingly, the performance test works fine in the default branch. \nAre you seeing the same issues? </p>", "type": "rendered"}, "created_on": "2016-07-13T18:02:08.441058+00:00", "user": {"display_name": "Hugo Boyer", "uuid": "{3d87874e-7099-4981-b04f-57f0272faa7d}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D"}, "html": {"href": "https://bitbucket.org/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/21198da8539b599e3633017f5f5f8150d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsHB-6.png"}}, "nickname": "hugomatic", "type": "user", "account_id": "557058:869c02bb-b246-4cdc-9db3-0064e8add185"}, "updated_on": "2016-07-13T18:02:08.443403+00:00", "type": "pullrequest_comment", "id": 20974642}