{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/gzweb.json"}, "html": {"href": "#!/osrf/gzweb"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3e2fc3f2-dc25-453b-9792-943c743d9b40}ts=1609263"}}, "type": "repository", "name": "gzweb", "full_name": "osrf/gzweb", "uuid": "{3e2fc3f2-dc25-453b-9792-943c743d9b40}"}, "links": {"attachments": {"href": "data/repositories/osrf/gzweb/issues/89/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/gzweb/issues/89.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gzweb/issues/89/watch"}, "comments": {"href": "data/repositories/osrf/gzweb/issues/89/comments_page=1.json"}, "html": {"href": "#!/osrf/gzweb/issues/89/roslaunch-gazebo-2-process-has-died-pid"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gzweb/issues/89/vote"}}, "reporter": null, "title": "roslaunch: [gazebo-2] process has died [pid 7605, exit code 139", "component": null, "votes": 0, "watches": 1, "content": {"raw": "After running my model with roslaunch for round about 10 to 20 minutes I always get the following error:   \r\n\r\n```\r\n#!\r\n\r\n\r\n    Segmentation fault (core dumped)  \r\n    [gazebo-2] process has died [pid 7605, exit code 139, cmd /opt/ros/kinetic/lib/gazebo_ros/gzserver -e ode /home/philipp/navibot_ws/src/navibot_gazebo/worlds/navibot.world __name:=gazebo __log:=/home/philipp/.ros/log/09e16ec0-4a76-11e7-a9fe-7085c23141c2/gazebo-2.log].  \r\n    log file: /home/philipp/.ros/log/09e16ec0-4a76-11e7-a9fe-7085c23141c2/gazebo-2*.log\r\n```\r\n\r\n\r\nUnfortunately no log file `gazebo-2*.log` is created.   \r\n\r\nI looked through my URDF model and checked my code. The problem is that I have a hard time to identify where the problem is really coming from, so I am looking for help here. I looked at the related questions here in the forum, but none of the solutions there worked for me.   \r\n\r\nThis is my backtrace:  \r\n\r\n```\r\n#!\r\n\r\n\r\n    Thread 25 \"gzserver\" received signal SIGSEGV, Segmentation fault.                   \r\n    [Switching to Thread 0x7fff67fff700 (LWP 28488)]\r\n    gazebo::physics::World::Update (this=this@entry=0x12075a0) at /build/gazebo-nhSAPd/g\r\n    740     /build/gazebo-nhSAPd/gazebo-7.0.0+dfsg/gazebo/physics/World.cc: No such file  \r\n    (gdb) backtrace  \r\n    0  gazebo::physics::World::Update (this=this@entry=0x12075a0) at /build/gazebo-nhSA  \r\n    1  0x00007ffff62d99af in gazebo::physics::World::Step (this=this@entry=0x12075a0) a  \r\n    2  0x00007ffff62d9e25 in gazebo::physics::World::RunLoop (this=0x12075a0) at /build  \r\n    3  0x00007ffff40d95d5 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.  \r\n    4  0x00007ffff65ee6ba in start_thread (arg=0x7fff67fff700) at pthread_create.c:333  \r\n    5  0x00007ffff6bef82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109  \r\n     (gdb) frame 0  \r\n    0  gazebo::physics::World::Update (this=this@entry=0x12075a0) at /build/gazebo-nhSAPd/gazebo-7.0.0+dfsg/gazebo  /physics/World.cc:740  \r\n    740     in /build/gazebo-nhSAPd/gazebo-7.0.0+dfsg/gazebo/physics/World.cc  \r\n    (gdb) frame 1  \r\n    1  0x00007ffff62d99af in gazebo::physics::World::Step (this=this@entry=0x12075a0) at /build/gazebo-nhSAPd/gazebo-7.0.0+dfsg/gazebo/physics/World.cc:672  \r\n    672     in /build/gazebo-nhSAPd/gazebo-7.0.0+dfsg/gazebo/physics/World.cc  \r\n    (gdb) frame 2  \r\n    2  0x00007ffff62d9e25 in gazebo::physics::World::RunLoop (this=0x12075a0) at /build/gazebo-nhSAPd/gazebo-  7.0.0+dfsg/gazebo/physics/World.cc:481  \r\n    481     in /build/gazebo-nhSAPd/gazebo-7.0.0+dfsg/gazebo/physics/World.cc  \r\n    (gdb) frame 3  \r\n    3  0x00007ffff40d95d5 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0  \r\n    (gdb) frame 4   \r\n    4  0x00007ffff65ee6ba in start_thread (arg=0x7fff67fff700) at pthread_create.c:333  \r\n    333     pthread_create.c: No such file or directory.  \r\n    (gdb) frame 5   \r\n    5  0x00007ffff6bef82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109  \r\n    109     ../sysdeps/unix/sysv/linux/x86_64/clone.S: No such file or directory.\r\n```\r\n\r\nAfterwards I ran my simulation headless on a stronger machine and the error occurred after 3 hours instead of 20 minutes.", "markup": "markdown", "html": "<p>After running my model with roslaunch for round about 10 to 20 minutes I always get the following error:   </p>\n<div class=\"codehilite\"><pre><span></span>    Segmentation fault (core dumped)  \n    [gazebo-2] process has died [pid 7605, exit code 139, cmd /opt/ros/kinetic/lib/gazebo_ros/gzserver -e ode /home/philipp/navibot_ws/src/navibot_gazebo/worlds/navibot.world __name:=gazebo __log:=/home/philipp/.ros/log/09e16ec0-4a76-11e7-a9fe-7085c23141c2/gazebo-2.log].  \n    log file: /home/philipp/.ros/log/09e16ec0-4a76-11e7-a9fe-7085c23141c2/gazebo-2*.log\n</pre></div>\n\n\n<p>Unfortunately no log file <code>gazebo-2*.log</code> is created.   </p>\n<p>I looked through my URDF model and checked my code. The problem is that I have a hard time to identify where the problem is really coming from, so I am looking for help here. I looked at the related questions here in the forum, but none of the solutions there worked for me.   </p>\n<p>This is my backtrace:  </p>\n<div class=\"codehilite\"><pre><span></span>    Thread 25 &quot;gzserver&quot; received signal SIGSEGV, Segmentation fault.                   \n    [Switching to Thread 0x7fff67fff700 (LWP 28488)]\n    gazebo::physics::World::Update (this=this@entry=0x12075a0) at /build/gazebo-nhSAPd/g\n    740     /build/gazebo-nhSAPd/gazebo-7.0.0+dfsg/gazebo/physics/World.cc: No such file  \n    (gdb) backtrace  \n    0  gazebo::physics::World::Update (this=this@entry=0x12075a0) at /build/gazebo-nhSA  \n    1  0x00007ffff62d99af in gazebo::physics::World::Step (this=this@entry=0x12075a0) a  \n    2  0x00007ffff62d9e25 in gazebo::physics::World::RunLoop (this=0x12075a0) at /build  \n    3  0x00007ffff40d95d5 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.  \n    4  0x00007ffff65ee6ba in start_thread (arg=0x7fff67fff700) at pthread_create.c:333  \n    5  0x00007ffff6bef82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109  \n     (gdb) frame 0  \n    0  gazebo::physics::World::Update (this=this@entry=0x12075a0) at /build/gazebo-nhSAPd/gazebo-7.0.0+dfsg/gazebo  /physics/World.cc:740  \n    740     in /build/gazebo-nhSAPd/gazebo-7.0.0+dfsg/gazebo/physics/World.cc  \n    (gdb) frame 1  \n    1  0x00007ffff62d99af in gazebo::physics::World::Step (this=this@entry=0x12075a0) at /build/gazebo-nhSAPd/gazebo-7.0.0+dfsg/gazebo/physics/World.cc:672  \n    672     in /build/gazebo-nhSAPd/gazebo-7.0.0+dfsg/gazebo/physics/World.cc  \n    (gdb) frame 2  \n    2  0x00007ffff62d9e25 in gazebo::physics::World::RunLoop (this=0x12075a0) at /build/gazebo-nhSAPd/gazebo-  7.0.0+dfsg/gazebo/physics/World.cc:481  \n    481     in /build/gazebo-nhSAPd/gazebo-7.0.0+dfsg/gazebo/physics/World.cc  \n    (gdb) frame 3  \n    3  0x00007ffff40d95d5 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0  \n    (gdb) frame 4   \n    4  0x00007ffff65ee6ba in start_thread (arg=0x7fff67fff700) at pthread_create.c:333  \n    333     pthread_create.c: No such file or directory.  \n    (gdb) frame 5   \n    5  0x00007ffff6bef82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109  \n    109     ../sysdeps/unix/sysv/linux/x86_64/clone.S: No such file or directory.\n</pre></div>\n\n\n<p>Afterwards I ran my simulation headless on a stronger machine and the error occurred after 3 hours instead of 20 minutes.</p>", "type": "rendered"}, "assignee": null, "state": "invalid", "version": null, "edited_on": null, "created_on": "2017-06-12T05:42:52.091778+00:00", "milestone": null, "updated_on": "2017-06-12T07:17:41.151790+00:00", "type": "issue", "id": 89}